<../../mkconfig

DIRS=\

TARG=\
	scgid.dis\
	testscgi.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	dict.m\
	draw.m\
	env.m\
	wait.m\
	sh.m\
	string.m\
	sys.m\


DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
